### ISSUE TITLE
Can't view images

### ISSUE THREAD

**Issue by sigues** [joselfonseca/image-manager#2]
When trying to view any thumbnail, I get 'Class Image not found'

http://screencloud.net/v/4okT

Thanks in advance

**Comment by joselfonseca** [comment]
Hey there!, that is because the alias for Intervention image is not registered, a quick solution is to add this in your composer.json file.

```
"intervention/image": "2.*",
"intervention/imagecache": "2.*"
```

run composer update and then in the providers array add.

```
'Intervention\Image\ImageServiceProvider'
```

Then in the aliases array

```
'Image' => 'Intervention\Image\Facades\Image'

```
 I will check the way to avoid this and update the docs next week.

Let me know

**Comment by sigues** [comment]
Worked like a charm, thanks man!
